version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api  # Use localhost for browser requests
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy  # Ensures DB is fully ready before backend starts
    environment:
      - DATABASE_URL=postgresql://todo_user:password123@db:5432/todo_app
      - JWT_SECRET=123
      - JWT_EXPIRES_IN=5h
    networks:
      - app_network

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: todo_app
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:  # Ensure the database is ready before backend starts
      test: ["CMD", "pg_isready", "-U", "todo_user"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  pg_data:

networks:
  app_network:
    driver: bridge
